export default {
    ADD_TODO: "ADD_TODO",
    REMOVE_TODO: "REMOVE_TODO",
    COMPLETE_TODO: "COMPLETE_TODO",
    UPDATE_TODO: "UPDATE_TODO",
    MODAL_CLEAR: "MODAL_CLEAR",
    MODAL_EDIT: "MODAL_EDIT",
    CLEAR_ALL_TODOS: "CLEAR_ALL_TODOS",
    DARK_MODE: "DARK_MODE"
} 